# Generated by Django 3.2 on 2021-05-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_auto_20210504_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attending', through='levelupapi.EventAttendee', to='levelupapi.Gamer'),
        ),
        migrations.AddField(
            model_name='gamer',
            name='attending_events',
            field=models.ManyToManyField(through='levelupapi.EventAttendee', to='levelupapi.Event'),
        ),
    ]
