# Generated by Django 3.2 on 2021-05-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_auto_20210504_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='attending_events',
        ),
        migrations.AlterField(
            model_name='event',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='levelupapi.game'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_host', to='levelupapi.gamer'),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='gamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_the_event', to='levelupapi.gamer'),
        ),
    ]
